
import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import NavBar from '../components/navbar';
import { manrope } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} flex flex-col min-h-screen`}>
        <ThemeProvider attribute='class' defaultTheme='system'>
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
